### ISSUE TITLE
Can you provide a method to find these parameters

### ISSUE THREAD

**Issue by MoonShadowIllusion** [Z4ee/HI3-ACE-B#1]
```cpp
		utils::write<uint32_t>(base_address + 0x106420, 0xCCC3C031);
		utils::write<uint8_t>(base_address + 0x102F40, 0xC3);
		utils::write<uint16_t>(base_address + 0x1BCC60, 0xFEEB);
```

**Comment by rwdsji** [comment]
> ```c++
> 		utils::write<uint32_t>(base_address + 0x106420, 0xCCC3C031);
> 		utils::write<uint8_t>(base_address + 0x102F40, 0xC3);
> 		utils::write<uint16_t>(base_address + 0x1BCC60, 0xFEEB);
> ```

I'd like to play HI3 again. Just a question, are those outdated?

**Comment by MoonShadowIllusion** [comment]
>  like

sorry.I don't know,I play the china version 
i have now implemented anti anti cheating in a somewhat cumbersome way

**Comment by Z4ee** [comment]
I don’t have this game on my PC right now and I don’t remember how I found these addresses, but I think you can do a bypass as I showed in https://github.com/Z4ee/StarRail-ACE-EMU

**Comment by MoonShadowIllusion** [comment]
ok
